[project]
name = "memeo"
version = "0.1.0"
description = "Memeo is a social network built for viral content, creativity, and community."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.4",
    "pillow>=12.2.0",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "django-types>=0.24.0",
]
