# Generated by Django 6.0.4 on 2026-05-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_remove_choice_votes_choice_votes_vote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
